-- 코드를 입력하세요
#SELECT * FROM ANIMAL_OUTS;

WITH RECURSIVE CTE AS 
(SELECT 0 AS HOUR  
 UNION ALL
 SELECT HOUR+1 FROM CTE
 WHERE HOUR<23)
 SELECT CTE.HOUR,IFNULL(D.COUNT,0) AS COUNT FROM CTE
 LEFT OUTER JOIN (SELECT HOUR(DATETIME) AS HOUR ,COUNT(*) AS COUNT FROM ANIMAL_OUTS GROUP BY HOUR) D ON D.HOUR = CTE.HOUR 