-- 코드를 입력하세요
#SELECT D.HOUR,COUNT(D.*) AS COUNT FROM 
#(SELECT DATE_FORMAT(DATETIME,"%H") AS HOUR FROM ANIMAL_OUTS) D
#GROUP BY D.HOUR
#ORDER BY D.HOUR
#;

SELECT D.HOUR,COUNT(*) AS COUNT FROM 
(SELECT HOUR(DATETIME) AS HOUR FROM ANIMAL_OUTS)D
WHERE D.HOUR BETWEEN 9 AND 19
GROUP BY D.HOUR
ORDER BY D.HOUR