-- 코드를 입력하세요
SELECT B.BOOK_ID,A.AUTHOR_NAME,
date_format(B.PUBLISHED_DATE,"%Y-%m-%d") as PUBLISHED_DATE
from BOOK B, AUTHOR A
WHERE CATEGORY = "경제" AND B.AUTHOR_ID = A.AUTHOR_ID
ORDER BY PUBLISHED_DATE